const sidebars = {
    docs: [
        'intro',
        {
            type: 'category',
            label: 'Проект',
            items: [
                'project/overview',
                'project/goals',
                'project/tech-stack',
                'project/repository-structure',
                'project/setup',
            ],
        },
        {
            type: 'category',
            label: 'Требования и сценарии',
            items: [
                'requirements/user-stories',
                'requirements/scope',
                'requirements/grading-checklist',
            ],
        },
        {
            type: 'category',
            label: 'Архитектура',
            items: [
                'architecture/overview',
                'architecture/auth-and-roles',
            ],
        },
        {
            type: 'category',
            label: 'База данных',
            items: [
                'database/erd',
                'database/models',
                'database/relationships',
                'database/normalization',
            ],
        },
        {
            type: 'category',
            label: 'Функциональность',
            items: [
                'features/recipes',
                'features/profile',
                'features/favorites',
                'features/cart',
                'features/comments',
                'features/articles',
                'features/chefs',
            ],
        },
        {
            type: 'category',
            label: 'REST API',
            items: [
                'api/overview',
                'api/authentication',
                'api/errors',
                'api/recipes-api',
                {
                    type: 'autogenerated',
                    dirName: 'api/reference',
                },
            ],
        },
        {
            type: 'category',
            label: 'Разработка',
            items: [
                'development/workflow',
                'development/commits',
                'development/future-roadmap',
            ],
        },
    ],
};

export default sidebars;